/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2020-04-16 09:00:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.controller.StudentListCtl;
import in.co.rays.controller.MarksheetCtl;
import in.co.rays.util.DataUtility;
import java.util.List;
import in.co.rays.util.ServletUtility;
import in.co.rays.util.HTMLUtility;
import java.util.HashMap;
import in.co.rays.dto.RoleDTO;
import in.co.rays.controller.LoginCtl;
import in.co.rays.controller.ORSView;
import in.co.rays.dto.UserDTO;

public final class CourseView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/Footer.jsp", Long.valueOf(1585492816476L));
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1587027283422L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("in.co.rays.controller.StudentListCtl");
    _jspx_imports_classes.add("in.co.rays.util.HTMLUtility");
    _jspx_imports_classes.add("in.co.rays.dto.RoleDTO");
    _jspx_imports_classes.add("in.co.rays.dto.UserDTO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("in.co.rays.util.ServletUtility");
    _jspx_imports_classes.add("in.co.rays.controller.LoginCtl");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("in.co.rays.controller.MarksheetCtl");
    _jspx_imports_classes.add("in.co.rays.controller.ORSView");
    _jspx_imports_classes.add("in.co.rays.util.DataUtility");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<!------ Include the above in your HEAD tag ---------->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.0.8/css/all.css\">\r\n");
      out.write("\r\n");
      out.write("<style  >\r\n");
      out.write(".divider-text {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-top: 15px;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write(".divider-text span {\r\n");
      out.write("    padding: 7px;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    position: relative;   \r\n");
      out.write("    z-index: 2;\r\n");
      out.write("}\r\n");
      out.write(".divider-text:after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-bottom: 1px solid #ddd;\r\n");
      out.write("    top: 55%;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-facebook {\r\n");
      out.write("    background-color: #405D9D;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write(".btn-twitter {\r\n");
      out.write("    background-color: #42AEEC;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body background=\"/Project_3/jsp/p3.png\">\r\n");
      out.write("\r\n");
 	String uri = (String)request.getAttribute("uri");
      out.write('\r');
      out.write('\n');
      in.co.rays.dto.CourseDTO dto = null;
      dto = (in.co.rays.dto.CourseDTO) _jspx_page_context.getAttribute("dto", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (dto == null){
        dto = new in.co.rays.dto.CourseDTO();
        _jspx_page_context.setAttribute("dto", dto, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.slim.min.js\" integrity=\"sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\" integrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\" integrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- fontawesome Library -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\"\r\n");
      out.write("\r\n");
      out.write("\tintegrity=\"sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write(" \r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("  <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write(" $(document).ready(function(){\r\n");
      out.write("\t    $('#select_all').on('click',function(){\r\n");
      out.write("\t        if(this.checked){\r\n");
      out.write("\t            $('.checkbox').each(function(){\r\n");
      out.write("\t                this.checked = true;\r\n");
      out.write("\t            });\r\n");
      out.write("\t        }else{\r\n");
      out.write("\t             $('.checkbox').each(function(){\r\n");
      out.write("\t                this.checked = false;\r\n");
      out.write("\t            });\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    $('.checkbox').on('click',function()\r\n");
      out.write("\t    {\r\n");
      out.write("\t        if($('.checkbox:checked').length == $('.checkbox').length){\r\n");
      out.write("\t            $('#select_all').prop('checked',true);\r\n");
      out.write("\t        }else{\r\n");
      out.write("\t            $('#select_all').prop('checked',false);\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t});\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

		UserDTO userDto = (UserDTO) session.getAttribute("user");

		boolean userLoggedIn = userDto != null;

		String welcomeMsg = "Hi,";

		if (userLoggedIn) {
			String role = (String) session.getAttribute("role");
			welcomeMsg += userDto.getFirstName() + " (" + role + ")";
		} else {
			welcomeMsg += "Guest";
		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\" >\r\n");
      out.write("<a href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\">\r\n");
      out.write("<div class=\" bg-light\" >\r\n");
      out.write("      <img  src=\"/Project_3/img/custom.png\" class=\" bg-light\"height=\"50px\" >\r\n");
      out.write("</div></a>&nbsp;&nbsp;&ensp;\r\n");
      out.write("<!--   <a class=\"navbar-brand\" href=\"#\">Navbar</a>\r\n");
      out.write(" --> \r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNavDropdown\" aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\r\n");
      out.write("    <ul class=\"navbar-nav  ml-auto mr-5\">\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("      ");

            if (userLoggedIn) {
        
      out.write("\r\n");
      out.write("          ");

if (userDto.getRoleId() == RoleDTO.STUDENT) {

      out.write("\r\n");
      out.write("\r\n");
      out.write("<li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("         <i class='fas fa-user'></i> User\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.USER_CTL);
      out.write("\"> <i class=\"fas fa-user-plus\"></i>Add User</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\"><i class=\"fas fa-users\"></i> User List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("         <i class='fas fa-file-alt' ></i> Marksheet\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Get Marksheet</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\"><i class=\"fas fa-user-tag\"></i>Marksheet MeritList</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\"><i class=\"fas fa-user-tag\"></i>Add Marksheet</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\"><i class=\"fas fa-list-ol\"></i>Marksheet List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      ");

}else if(userDto.getRoleId()==RoleDTO.ADMIN){

      out.write("\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("         <i class='fas fa-user'></i> User\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.USER_CTL);
      out.write("\"> <i class=\"fas fa-user-plus\"></i>Add User</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\"><i class=\"fas fa-users\"></i> User List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("         <i class='fas fa-file-alt' ></i> Marksheet\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("<!--           <a class=\"dropdown-item\" href=\"#\">Get Marksheet</a>\r\n");
      out.write(" -->          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\"><i class=\"fas fa-user-tag\"></i>Marksheet MeritList</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\"><i class=\"fas fa-file-alt\"></i>Add Marksheet</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\"><i class=\"fas fa-list-ol\"></i>Marksheet List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("       <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("         <i class='fas fa-university'></i> College\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COLLEGE_CTL);
      out.write("\"><i class=\"fa fa-university\"></i>Add College</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\"><i class=\"fas fa-list-ol\"></i>College List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("         <i class='fas fa-user-circle'></i>  Role\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_CTL);
      out.write("\"><i class=\"fas fa-user-circle\"></i>Add Role</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_LIST_CTL);
      out.write("\"><i class=\"fas fa-list-ol\"></i>Role List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("       <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("        <i class='fas fa-user-graduate'></i>  Student\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\"><i class=\"fas fa-user-graduate\"></i>Add Student</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\"><i class=\"fas fa-users\"></i>Student List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("         <i class='fa fa-book'></i> Course\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COURSE_CTL);
      out.write("\"><i class=\"fas fa-book\"></i>Add Course</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\"><i class=\"fas fa-list-ol\"></i>Course List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("           <i class='fas fa-book'></i> Subject\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.SUBJECT_CTL);
      out.write("\"><i class=\"fas fa-book\"></i>Add Subject</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\"><i class=\"fas fa-list-ol \"></i>Subject List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("         <i class='fas fa-user-tie'></i> Faculty\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.FACULTY_CTL);
      out.write("\"><i class=\"fas fa-user-tie\"></i>Add Faculty</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\"><i class=\"fas fa-users\"></i>Faculty List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item dropdown \">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("         <i class='fas fa-clock'></i> TimeTable\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.TIME_TABLE_CTL);
      out.write("\"><i class=\"fas fa-clock\"></i>Add TimeTable</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.TIME_TABLE_LIST_CTL);
      out.write("\"><i class=\"fas fa-list-ol \"></i>TimeTable List</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("       \r\n");
      out.write("  ");

            }
            }
        
      out.write("\r\n");
      out.write("       <li class=\"nav-item dropdown \" >\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("<i class=\"fas fa-user-circle\"></i>\r\n");
      out.write("          ");
      out.print(welcomeMsg);
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("          ");

if(userLoggedIn){
      
      out.write("\r\n");
      out.write("       <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink \" style=\"top: 128% ; left: 30px\">\r\n");
      out.write("       \r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\"><i class=\"fa fa-user-secret\" aria-hidden=\"true\"></i>My Profile</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL);
      out.write("\"><i class=\"fa fa-key\"></i>Change Password</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.JAVA_DOC_VIEW);
      out.write("\" target=\"_blank\"><i class=\"fas fa-file-alt \"></i>Java Doc</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("?operation=");
      out.print(LoginCtl.OP_LOG_OUT);
      out.write("\"><i class=\"fas fa-sign-out-alt\"></i>Logout</a>\r\n");
      out.write("       </div>\r\n");
      out.write("          ");

						} else {
					
      out.write(" \r\n");
      out.write("           <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink \" style=\"top: 128% ; left: -32px\">\r\n");
      out.write("       \r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\"><i class=\"fas fa-sign-in-alt\"></i>login</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.USER_REGISTRATION_CTL);
      out.write("\"><i class=\"fa fa-registered\"></i>User Registration</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.FORGET_PASSWORD_CTL);
      out.write("\"><i class=\"fa fa-key\"></i>Forget Password</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("   \r\n");
      out.write("      </ul>\r\n");
      out.write("     </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"card bg-secondary text-white mx-auto\" style=\"max-width: 400px; \" >\r\n");
      out.write("<article class=\"card-body mx-auto\" style=\"max-width: 400px;\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"");
      out.print(ORSView.COURSE_CTL);
      out.write("\" method=\"post\">\r\n");
      out.write("\t<!-- getting role list for preload -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("                        ");
long id=DataUtility.getLong(request.getParameter("id")); 
      out.write("\r\n");
      out.write("                      \r\n");
      out.write("                           <h3 class=\"text-center default-text py-3\">");
      out.print((id==0)? "Add Course": "Update Course" );
      out.write("</h3>\r\n");
      out.write("                            \r\n");
      out.write("                          \r\n");
      out.write("                            <!--Body-->\r\n");
      out.write("                            \r\n");
      out.write("                            \t\t");
if(!ServletUtility.getSuccessMessage(request).equals("")){ 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-success alert-dismissible fade show\">\r\n");
      out.write("    <button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\r\n");
      out.write("    <strong>Success!</strong>");
      out.print(ServletUtility.getSuccessMessage(request) );
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
} 
      out.write("                            \r\n");
      out.write("\t\r\n");
      out.write("\t");
if(!ServletUtility.getErrorMessage(request).equals("")){ 
      out.write("\r\n");
      out.write("<div class=\"alert alert-danger\">\r\n");
      out.write("    <button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\r\n");
      out.write("    <strong>Error!</strong><font>");
      out.print(ServletUtility.getErrorMessage(request) );
      out.write("</font>\r\n");
      out.write("  </div>\r\n");
} 
      out.write("                            \r\n");
      out.write("\t\t\r\n");
      out.write("            <input type=\"hidden\" name=\"id\" value=\"");
      out.print(dto.getId());
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"createdBy\" value=\"");
      out.print(dto.getCreatedBy());
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"modifiedBy\" value=\"");
      out.print(dto.getModifiedBy());
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"createdDatetime\" value=\"");
      out.print(DataUtility.getTimestamp(dto.getCreatedDateTime()));
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"modifiedDatetime\" value=\"");
      out.print(DataUtility.getTimestamp(dto.getModifiedDateTime()));
      out.write("\">\r\n");
      out.write("         \r\n");
      out.write("         <h6 style=\"color: #20B2AA\">Course Name<font color=\"red\">*</font></h6>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"input-group mb-3\">                   \r\n");
      out.write("\t<div class=\"form-group input-group\">\r\n");
      out.write("\t\t<div class=\"input-group-prepend\">\r\n");
      out.write("\t\t    <span class=\"input-group-text\"> <i class=\"fa fa-book\"></i> </span>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("        <input name=\"courseName\" class=\"form-control\" placeholder=\"Enter Course Name\" type=\"text\" value=\"");
      out.print(DataUtility.getStringData(dto.getCourseName()));
      out.write("\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <font color=\"red\" class=\"ml-5\">");
      out.print(ServletUtility.getErrorMessage("courseName",request) );
      out.write(" </font>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- form-group// -->\r\n");
      out.write("  \r\n");
      out.write("       <h6 style=\"color: #20B2AA\">Description<font color=\"red\">*</font></h6>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"input-group mb-3\">                   \r\n");
      out.write("\t<div class=\"form-group input-group\">\r\n");
      out.write("\t\t<div class=\"input-group-prepend\">\r\n");
      out.write("\t\t    <span class=\"input-group-text\"> <i class=\"fa fa-bars\"></i> </span>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("        <textarea name=\"description\" class=\"form-control\" placeholder=\"Enter description\" type=\"text\" value=\"");
      out.print(DataUtility.getStringData(dto.getDescription()));
      out.write("\"></textarea>\r\n");
      out.write("    </div>\r\n");
      out.write("    <font color=\"red\" class=\"ml-5\">");
      out.print(ServletUtility.getErrorMessage("description",request) );
      out.write(" </font>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- form-group// -->\r\n");
      out.write("      \r\n");
      out.write("      <h6 style=\"color: #20B2AA\">Duration<font color=\"red\">*</font></h6>\r\n");
      out.write("         \r\n");
      out.write("          ");
HashMap<String,String> map = new HashMap<String,String>();
							map.put("1y", "1year");
							map.put("2y", "2year");
							map.put("3y", "3year");
							map.put("4y", "4year");
							map.put("5y", "5year");
							String HtmlList = HTMLUtility.getList("duration", dto.getDuration(), map);
					
      out.write("          \r\n");
      out.write("         \r\n");
      out.write("         <div class=\"input-group mb-3\">                   \r\n");
      out.write("\t<div class=\"form-group input-group\">\r\n");
      out.write("\t\t<div class=\"input-group-prepend\">\r\n");
      out.write("\t\t    <span class=\"input-group-text\"> <i class=\"fa fa-clock\"></i> </span>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t\t \t");
      out.print(HtmlList);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <font color=\"red\" class=\"ml-5\">");
      out.print(ServletUtility.getErrorMessage("duration",request) );
      out.write(" </font>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- form-group// -->\r\n");
      out.write("      \r\n");
      out.write(" \r\n");
      out.write("      ");
if (id>0){ 
      out.write("                                   \r\n");
      out.write("    <div class=\"form-group \" align=\"center\">\r\n");
      out.write("        <input type=\"submit\" class=\"bg-success text-white\" name=\"operation\" value=\"");
      out.print(MarksheetCtl.OP_UPDATE);
      out.write("\">   \r\n");
      out.write("                <input type=\"submit\" class=\"bg-warning text-white\"  name=\"operation\" value=\"");
      out.print(MarksheetCtl.OP_CANCEL);
      out.write("\">\r\n");
      out.write("     </div> <!-- form-group// -->  \r\n");
      out.write("   \r\n");
      out.write("   ");
}else{ 
      out.write(" \r\n");
      out.write("   <div class=\"form-group \" align=\"center\">\r\n");
      out.write("        <input type=\"submit\" class=\"bg-success text-white\" name=\"operation\" value=\"");
      out.print(MarksheetCtl.OP_SAVE);
      out.write("\">   \r\n");
      out.write("                <input type=\"submit\" class=\"bg-warning text-white\"  name=\"operation\" value=\"");
      out.print(MarksheetCtl.OP_RESET);
      out.write("\">\r\n");
      out.write("     </div> <!-- form-group// -->  \r\n");
      out.write("   ");
} 
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</form>\r\n");
      out.write("</article>\r\n");
      out.write("</div> <!-- card.// -->\r\n");
      out.write("\r\n");
      out.write("</div> \r\n");
      out.write("<!--container end.//-->\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.0.8/css/all.css\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#footer {\r\n");
      out.write("\r\n");
      out.write("      height:-8px;\r\n");
      out.write("   /*  clear: both; */\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    /* height: 70px; */\r\n");
      out.write("    width:100%;\r\n");
      out.write("    bottom:0;\r\n");
      out.write("  /*   margin-top: 240px; */\r\n");
      out.write("  text-align: center;\r\n");
      out.write("   background-color: black ; \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id =\"footer\">\r\n");
      out.write("<CENTER>\r\n");
      out.write("    <font style=\"font-family: serif;\" color=\"darkgray\"><H4 >&copy; Copyrights RAYS Technologies</H3></font>\r\n");
      out.write("</CENTER>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
